export { default as MaskedArrivalBg } from './images/arrival-bg.png'
export { default as ArrivalLady } from './images/arrival-lady.png'
export { default as ArrowIcon } from './vectors/arrow.svg'
export { default as BasketIcon } from './vectors/basket.svg'
export { default as SearchIcon } from './vectors/search.svg'
